- name: SquidGame
  hosts: virtualmachines
  tasks:
  #- name: Update repository
  #   apt_repository:
  #    repo: 'ppa:git-core/ppa'
  #    state: present

   - name: Install Git
     become: yes 
     become_method: sudo
     apt:
       name: git
       state: present
       update_cache: yes
     vars:
       ansible_user: account

   - name: Clone a github repo
     ansible.builtin.git:
       repo: git@github.com:AndyTwelve/dos14-gramovich-git-flow.git
       dest: /tmp/dos14-gramovich-git-flow
       clone: yes
       update: yes
