- name: My first play
  hosts: virtualmachines
  tasks:
  # - name: Ping my hosts
  #   ansible.builtin.ping:
  # - name: Print message
  #   ansible.builtin.debug:
  #     msg: Hello world

  # - name: Update repository
  #   apt_repository:
  #    repo: 'ppa:git-core/ppa'
  #    state: present
   - name: Install Git
     apt:
      name: git
      state: present
      update_cache: yes
